version: '3.7'

services:
  app:
    build: ./services/app
    volumes:
      - /home/kip/src/app/.venv
      - ./services/app:/home/kip/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.app_env.dev
    depends_on:
      - db
      - data-provider
  data-provider:
    build: ./services/data-provider
    volumes:
      - /home/kip/src/data/.venv
      - ./services/data-provider:/home/kip/src/data/
    ports:
      - 8000:8000
    env_file:
      - ./.data_provider_env.dev
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sudoku_dev
      - POSTGRES_PASSWORD=sudoku_dev
      - POSTGRES_DB=sudoku_dev

volumes:
  postgres_data:





