version: '3.7'

services:
  app:
    build: ./services/app
    command: poetry run python manage.py run -h 0.0.0.0 --port=5000
    volumes:
      # - ./services/app:/home/kip/src/app/
      - ./services/app/project:/home/kip/src/app/project/
      - ./services/app/static:/home/kip/src/app/static/
      - ./services/app/templates:/home/kip/src/app/templates/
      - ./services/app/tests:/home/kip/src/app/tests/
    ports:
      - 5000:5000
    env_file:
      - ./.app_env.dev
    depends_on:
      - db
      - data-provider
  data-provider:
    build: ./services/data-provider
    command: poetry run python app.py run -h 0.0.0.0 --port=8000
    volumes:
      - ./services/data-provider:/home/kip/src/data/
    ports:
      - 8000:8000
    env_file:
      - ./.data_provider_env.dev
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sudoku_dev
      - POSTGRES_PASSWORD=sudoku_dev
      - POSTGRES_DB=sudoku_dev

volumes:
  postgres_data:





